name: GitHub Pages Deploy

on:
  push:
    branches: [ develop ]

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-base-folder: 'public'
          commit-message: 'Automatic deploy'
          branch: 'main'