name: GitHub Pages Deploy

on:
  push:
    branches:
      - Xmain

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: rdarida/simple-github-pages-deploy-action@v1
        with:
          git-user: 'github-actions[bot]'
          git-email: 'github-actions[bot]@users.noreply.github.com'
          git-base-folder: 'out'
          commit-message: 'Automatic deploy'
